backend/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','update','delete','view','create'),
				'users'=>  UserRoleConstant::getAdminUserList()
			),		
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
        if(Yii::app()->user->checkAccess(UserRoleConstant::CREATE_USER_TASK)){
            $model=new User('admin');		
            if(isset($_POST['User']))
            {
                $lastRole = $model->role;
                $model->attributes=$_POST['User'];
                
                if($model->save()){
                    UserMetaUtil::updateMetaByPost($model);
                    $this->updateUserAccess($model,$lastRole);
                    $this->redirect(array('view','id'=>$model->id));
                }
                    
            }
            $this->render('create',array(
                'model'=>$model,
            ));
        }
		
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
        if(Yii::app()->user->checkAccess(UserRoleConstant::UPDATE_USER_TASK)){
            
            $model=$this->loadModel($id);
            
            if(isset($_POST['User']))
            {
                $lastRole = $model->role;
                $model->attributes=$_POST['User'];
                if($model->save()){
                    UserMetaUtil::updateMetaByPost($model);
                    $this->updateUserAccess($model,$lastRole);
                    $this->redirect(array('update','id'=>$model->id));
                }
            }
            $model->password = '';
              
            $this->render('update',array(
                'model'=>$model,
            ));
        }
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
        if(Yii::app()->user->checkAccess(UserRoleConstant::DELETE_USER_TASK)){
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
		
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{                
        //Yii::app()->authManager->assign('mod',15);
        if(Yii::app()->user->checkAccess(UserRoleConstant::VIEW_USER_TASK)){
            $model=new User('search');
            $model->unsetAttributes();  // clear any default values
            if(isset($_GET['User']))
                $model->attributes=$_GET['User'];

            $this->render('index',array(
                'model'=>$model,
            ));
        }
		
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);        
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
        $model->setScenario('admin');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
    
    protected function updateUserAccess($user,$lastRole){
        $lastRoleName = UserRoleConstant::getRoleName($lastRole);
        
        Yii::app()->authManager->revoke(strtolower($lastRoleName),$user->id);
        $roleName = UserRoleConstant::getRoleName($user->role);        
        Yii::app()->authManager->assign(strtolower($roleName),$user->id);
        
    }
    
  
}

frontend/controllers/UserController.php
<?php

class UserController extends Controller
{

    protected $_user;

    public function behaviors()
    {
        return array(
            'seo' => array('class' => 'frontend.extensions.seo.components.SeoControllerBehavior')
        );
    }

    public function actions()
    {
        return array(
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => '0xFFFFFF',
                'transparent' => true,
                'testLimit' => 5
            )
        );
    }

    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(array('/site'));
    }

    public function actionLogin($returnUrl = null)
    {
        if (Yii::app()->user->isGuest == false) {
            //$this->redirect('/site/index');
        }
        $loginForm = new LoginForm();
        if (isset($_POST['LoginForm'])) {
            $loginForm->username = $_POST['LoginForm']['username'];
            $loginForm->password = $_POST['LoginForm']['password'];
            if ($loginForm->validate() && $loginForm->login()) {
                //a login user by email can still be a facebook user
               
                    
                    if ($this->hasReturnUrl()) {
                        $this->redirectToReturnUrl();
                    }
                    else {
                        $siteUrl = $this->createUrl('/site/index');
                        $this->redirect($siteUrl);
                    }
                
                
            }
            $loginForm->password = '';
        }
        $this->render('login', array(
            'model' => $loginForm,
            'returnUrl' => $this->returnUrl,
        ));
    }

    public function actionFacebookLogin()
    {
        $this->render('facebookLogin', array(
            'returnUrl' => $this->returnUrl,
        ));
    }

    public function actionFbProfile()
    {
        
    }

    public function actionBindAccountFacebook()
    {
        if (isset($_GET['code'])) {
            try {
                $profile = Yii::app()->facebook->api('/me');
                if (Yii::app()->user->isGuest == false) {
                    $currentUser = Yii::app()->user->model;
                    $currentUser->fbId = $profile['id'];
                    $currentUser->save();
                    Yii::app()->controller->redirect(Yii::app()->controller->getReturnUrl());
                }
            }
            catch (FacebookApiException $e) {
                // in here you can look at the Exception $e, and determine if it's an expired
                // access token error, and if it is, you can redirect your user somewhere to
                // re-authenticate if you want - either by redirecting them to the login page,
                // or by showing a Flash message with the JavaScript Login button, etc
                //echo $e->getMessage();
                Yii::app()->controller->redirect(FacebookUtil::getInstance()->makeFacebookLoginUrlNew(Yii::app()->controller->getReturnUrl()));
            }
        }
    }

    public function actionRegister()
    {       
        if (isset($_GET['code'])) {
            try {
                $accessToken = Yii::app()->facebook->getAccessToken();
                $profile = Yii::app()->facebook->api('/me'); 
                
                if (isset($profile['email'])) {
                    $newFacebookuser = false;
                    if (Yii::app()->user->isGuest == false) {
                        $user = Yii::app()->user->getModel();                        
                    }
                    else {
                        $user = UserUtil::getUserByEmail($profile['email']);
                    }
                    if ($user == null) {
                        $user = new User();
                        $user->email = $profile['email'];
                        $user->password = StringUtil::generateRandomString(25);
                        $original = $profile['first_name'] . ' ' . $profile['last_name'];
                        $username = $original;
                        $increment = 1;
                        while (UserUtil::isUserNameExist($username)) {
                            $username = $original . '.' . $increment;
                            $increment++;
                        }
                        $user->username = $username;
                        Yii::app()->session['LastFbId'] = $profile['id'];
                        $user->fbId = $profile['id'];
                        $user->isFbUser = 1;
                        $newFacebookuser = true;
                    }
                    else {
                        
                        $user->fbId = $profile['id'];
                        $user->isFbUser = 1;
                    }

                    $user->save();
                    FacebookUtil::getInstance()->saveUserToken($user->id, $accessToken);
                    FacebookUtil::getInstance()->setExtendedAccessToken();
                    Yii::app()->session['CheckedAccessToken'] = true;
                    $loginForm = new FacebookLoginForm();
                    $loginForm->username = $user->email;
                    $loginForm->validate();
                    $loginForm->login();
                    Yii::app()->user->setFlash('success','Kết nối với Facebook thành công.');
                    $siteUrl = $this->createUrl('/site',array('id'=>$user->id,'newUser'=>true));                    
                    if($newFacebookuser){
                        $this->redirect($siteUrl);
                    }else{
                        if($this->hasReturnUrl()){
                            $this->redirectToReturnUrl();                        
                        }
                    }                    
                }
            }
            catch (FacebookApiException $e) {               
                Yii::app()->user->setFlash('error','Kết nối với Facebook bị lỗi, vui lòng thử lại sau.');
                $this->redirect($this->createUrl('/user/login'));
            }
        }
        $user = new User('register');
        if (isset($_POST['User'])) {
            $user->attributes = $_POST['User'];
            if (isset(Yii::app()->session['LastFbId'])) {
                $user->fbId = Yii::app()->session['LastFbId'];
            }
            $password = $_POST['User']['password'];
            $user->setScenario('register');
            if ($user->save()) {
                Yii::app()->user->setFlash('success', 'Chúc mừng bạn đã đăng ký thành công');
                $loginForm = new LoginForm();
                $loginForm->username = $user->email;
                $loginForm->password = $password;
                $loginForm->validate();
                $loginForm->login();
                $siteUrl = $this->createUrl('/site');
                $this->redirect($siteUrl);
            }
        }
        $user->password = '';
        $this->render('register', array(
            'user' => $user
        ));
    }

    public function actionProfile($id)
    {
        $user = $this->loadUser($id);
        //load product,sort by time
        if($user->phone==NULL && $user->address!=NULl ){
            $phone = $user->address[0]->phone;
            Yii::app()->db->createCommand()->update('mp_user', array(
                'phone'=>$phone,
            ), 'id=:id', array(':id'=>$id));
        }
        $productDataProvider = $user->searchProduct(null, 20, 0);
        $this->render('profile', array(
            'productDataProvider' => $productDataProvider,
            'page' => 0,
            'category' => null,
            'user' => $user
        ));
    }

    public function actionUserProductList($userId, $page = 0)
    {
        $user = $this->loadUser($userId);
        $dataProvider = $user->searchProduct(null, 10, $page);
        $productList = $dataProvider->getData();
        $empty = $page >= $dataProvider->pagination->pageCount;        
        if (!$empty) {
            $html = '';
            foreach($productList as $product){
                $html.=$product->renderHtml('',true);
            }
            $this->renderAjaxResult(true,array(
                'items'=>$html,
                'count'=>count($productList)
            ));
            Yii::app()->end();
        }else{
            $this->renderAjaxResult(true,array(
                'items'=>'',
                'count'=>0
            ));
        }
    }

    protected function loadUser($id)
    {
        if ($this->_user == null) {
            $this->_user = User::model()->findByPk($id);
            if ($this->_user == null) {
                throw new CHttpException(404, 'User not found');
            }
        }
        return $this->_user;
    }

    public function actionUploadProfileImage()
    {
        if (Yii::app()->user->isGuest == false) {
            $user = Yii::app()->user->model;
            $result = UserUtil::uploadProfile($user);
            if ($result) {
                $this->renderAjaxResult(true, Yii::app()->baseUrl . '/' . $user->image);
            }
            $this->renderAjaxResult(false, array('error' => $user->getErrors()));
        }
    }

    public function actionUploadBannerImage()
    {
        if (Yii::app()->user->isGuest == false) {
            $user = Yii::app()->user->model;
            if (UserUtil::uploadBanner($user)) {
                $this->renderAjaxResult(true, Yii::app()->baseUrl . '/' . $user->getBanner());
            }
            else {
                $this->renderAjaxResult(false, array('errors' => $user->getError('banner')));
            }
        }
    }

    public function actionForgetPassword()
    {

frontend/views/user/_changeSlugDialog.php
<div class="row-fluid">    
    <div class="modal hide fade" id='slugDialog' style="top:20%;">    

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Chọn địa chỉ cho trang cá nhân của bạn</h3>
  </div>
        <div class="modal-body">            
            <p>Hãy chọn địa chỉ cho trang cá nhân của bạn.<br/>
Chỉ được sử dụng tiếng Việt không dấu, số và dấu gạch ngang. Bạn chỉ được chọn một lần duy nhất.</p>
            <p>
                Ví dụ http://itake.me/<b><span id="newSlug"><?php echo $defaultSlug; ?></span></b>
            </p>
            <?php echo CHtml::textField('slug',''); ?>
        </div>
        <div class="modal-footer">
            
            <?php echo CHtml::link('Lưu lại','#',array(
                'class'=>'btn btn-success',                
                'id'=>'btnSaveSlug'
            ));?>
            <a href="#" data-dismiss="modal" class="btn"><?php LanguageUtil::echoT('Close') ?></a>
            
        </div>
    
    </div>
</div>

frontend/views/user/_formProfile.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>


<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'user-_formProfile-form',
	'enableAjaxValidation'=>false,
    'type'=>'vertical',
    'htmlOptions'=>array('class'=>'form itake-form','role'=>'form'),
)); ?>

	<!-- <p class="note">Fields with <span class="required">*</span> are required.</p>
 -->
    <fieldset>
	<?php echo $form->errorSummary($model); ?>
       <div class="row-fluid">
        <div class="span6">
            <div class="control-group">
    		    <?php echo $form->textFieldRow($model,'username',array('class'=>'controls','labelOptions'=>array('class'=>'control-label'))); ?>
            </div>                     
            <div class="control-group">
    		    <?php echo $form->dropDownListRow($model,'city',  CityUtil::getCityListData(true),array('class'=>'controls','labelOptions'=>array('class'=>'control-label'))); ?>
            </div>
            <div class="control-group">
    		    <?php echo $form->textFieldRow($model,'locationText',array('class'=>'controls','labelOptions'=>array('class'=>'control-label'))); ?>
            </div>
            </div>
            <div class="span6">
            <div class="control-group">
    		    <?php echo $form->textFieldRow($model,'phone',array('class'=>'controls','labelOptions'=>array('class'=>'control-label'))); ?>
            </div>

            <div class="control-group">
    		    <?php echo $form->textAreaRow($model,'target',array('rows'=>3,'class'=>'controls','labelOptions'=>array('class'=>'control-label'))); ?>
            </div>
            <div class="control-group">
                <label class="control-label"><?php LanguageUtil::echoT('Password') ?></label>    
                <div class="controls"> 
                <?php echo CHtml::link(LanguageUtil::t('Change password'),$this->createUrl('user/changePassword'),array(
                            'class'=>'btn btn-primary',
                        )); ?>
                </div> 
            </div>
            </div>
        </div>
    <hr>
	<div class="control-group margin-top-20">
        <div class="controls">
		  <?php echo CHtml::submitButton(LanguageUtil::t('Update'),array('class' => 'btn btn-success btn-large')); ?>
          <?php if(isset($_GET['newUser']) && $_GET['newUser']) echo CHtml::link('Bỏ qua bước này',Yii::app()->createUrl('/site'),array('class' => 'btn btn-large')); ?>
        </div>
	</div>
    </fieldset>
<?php $this->endWidget(); ?>

<!-- form -->

frontend/views/user/_userProductBoard.php
<?php
$script = <<<HERE
var page = 1;      
var stopLoad = false;        
$(document).ready(function() {
    var board = $('#userProductBoard');
    board.isotope({
        columnWidth: 10,
        itemSelector: '.productItem',
        transformsEnabled:true,
        straightAcross: {
            rowHeight: 160
        }
    });
    board.isotope('reLayout');    
        
    setInterval(function(){
        $('#userProductBoard').isotope('reLayout');
    },500);
        
    initCheckBottom(function(){
        if(false == stopLoad){
            showMessage('Đang lấy thêm sản phẩm...',1000);
            page++;
            $.ajax({
                url:BASE_URL + '/user/userProductList',
                data:{
                    page:page,
                    userId:user.id
                },
                success:function(jsons){
                    var data = $.parseJSON(jsons);
                    if(data.success){
                        if(data.msg.count > 0){                        
                            board.isotope('insert',$(data.msg.items));                 
                        }else{
                            stopLoad = true;
                            showMessage("Không còn sản phẩm nào nữa để tải");
                        }

                    }
                }
            });
        }else{
            showMessage("Không còn sản phẩm nào nữa để tải");
        }        
    });
   
   
});
HERE;
Yii::app()->clientScript->registerScript('userProductList', $script, CClientScript::POS_END);
?>
<div id="userProductBoard" class='productBoard margin-top-20' style="display:none;">
    <?php foreach ($productList as $userProduct): ?>        
        <?php echo $userProduct->renderHtml("", true); ?>        
    <?php endforeach; ?>
</div>
<?php
echo CHtml::link(
        'Next', array(
    '/user/userProductList',
    'userId' => $user->id,
    'page' => $page
        ), array(
    'class' => 'currentUserProductLink',
    'style' => 'display:none'
));
echo CHtml::link(
        'current', 
        array(
            '/user/userProductList',
            'userId' => $user->id,
            'page' => $page + 1
        ), array(
            'class' => 'nextUserProductLink',
            'style' => 'display:none'
        )
);
;
?>

frontend/views/user/changePassword.php
<?php 
$this->pageTitle = LanguageUtil::t('Change password').' ITAKE';
//$this->showHeader = false;
?>

<div class="container more-space" style="margin-top:54px;">
    <?php 

    $this->widget('bootstrap.widgets.TbAlert', array(
        'block'=>true, 
        'fade'=>true, 
        'closeText'=>'×',
        'alerts'=>array( 
            'error'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), 
            'success'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), 
        ),
    ));
    ?>
    <?php $form= $this->beginWidget('bootstrap.widgets.TbActiveForm',array(
    	'htmlOptions'=>array(
    		'class'=>'form-signin'
    	)
    ));?>
        <h2 class="form-signin-heading"><?php  LanguageUtil::echoT('Change password')?> </h2>
               
        <?php echo $form->errorSummary($model); ?>
        <?php if( $model->hideOldPassword == false):?>
            <?php echo $form->passwordFieldRow($model,'oldPassword',array(
            'placeholder'=> LanguageUtil::t('Old password'),
            'class'=>'input-block-level'
            )); ?>
        <?php else:?>
            <p>Nếu bạn đăng nhập từ Facebook và đây là lần đầu tiên đổi mật khẩu, thì bạn chỉ cần nhập mật khẩu mới. <br/>Mật khẩu này giúp bạn đăng nhập mỗi khi Facebook gặp sự cố.</p>
        <?php endif; ?>
        
        <?php echo $form->passwordFieldRow($model,'password',array(
        'placeholder'=>LanguageUtil::t('New password'),
        'class'=>'input-block-level'
        )); ?>
        
        <?php echo $form->passwordFieldRow($model,'retypePassword',array(
        'placeholder'=>LanguageUtil::t('Reconfirm new password'),
        'class'=>'input-block-level'
        )); ?>
      
        
        <button class="btn btn-primary btn-large pull-right" type="submit"><?php LanguageUtil::echoT('Update') ?></button>
        
     <?php $this->endWidget(); ?> 

</div>

frontend/views/user/editProfile.php
<?php
Yii::app()->clientScript->registerScript('changeslug','var canChangeSlug = '.CJavaScript::encode($canChangeSlug),  CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/nada/user.js',CClientScript::POS_BEGIN);
$this->pageTitle = 'Chỉnh sửa thông tin cá nhân';
?>
<div class='container-fluid'>
	<div class="row-fluid">
		<div class="span12 center ">
      <div class="avatar">
        <?php
            echo UserImageUtil::renderImage($model,array(
            'width' => 70,
            'height' => 70,
            'style' => 'width: 100px;
            height: 100px;',
            'class' => 'img-circle',
            ));
        ?>
		</div>
  </div>
		<h1 class="title_font center" style="color:gray;font-size:1.8em;">
			CẬP NHẬT THÔNG TIN TÀI KHOẢN ITAKE
		</h1>
        <?php if($newUser):?>
        
        <?php endif; ?>
	</div>
	<div class="span8 offset3" id="profile"> 
        <center>
        <p class="alert-success alert">
            Chúc mừng bạn đã đến với itake.me, hãy dành ít phút để cập nhật thông tin của bạn
        </p>
        </center>
    <hr>
    <br>
  	<?php $this->renderPartial('_formProfile',array('model'=>$model)); ?>
	</div>
</div>
<?php if($canChangeSlug):?>
    <?php $this->renderPartial('_changeSlugDialog',array(
        'defaultSlug'=>$defaultSlug
    ));?>
<?php endif; ?>

frontend/views/user/facebookLogin.php
<?php
$this->pageTitle = LanguageUtil::t('Sign In').' ITAKE';

//$this->showHeader = false;
?>
<div class="container-fluid" style="margin-top: 74px;">
    <div class="row-fluid">
        <div class="span8 offset2">
        <h2 class="form-signin-heading"><i class="icon-signin"></i>  <?php LanguageUtil::echoT('Sign In'); ?></h2>          
        <hr/>
        </div>
    </div>
    <div class="row-fluid">
          
        <div class="span8 offset2">
             <div style="width:100%;margin-top: 40px;">
            <!--     <p style="font-family: 'Segoe UI Light',Arial,Helvetica,sans-serif;font-size:1.1em;">Dễ dàng chia sẽ tin đăng. ITAKE kết nối tới facebook của bạn để việc bán hàng của bạn nhanh chóng hơn, tiếp thị sản phẩm thêm hiệu quả. Hãy đăng nhập bằng facebook để chia sẻ sản phẩm bạn tới bạn bè trên facebook một cách tốt nhất.</p> -->                                
                <div class="fb-login-wrapper"> 
                    <?php if(Yii::app()->language=='vi'): ?>
                    <?php echo CHtml::link('', FacebookUtil::makeFacebookLoginUrl($returnUrl), array('class' => 'facebook-login')); ?>       
                    <?php else: ?>            
                      <?php echo CHtml::link('', FacebookUtil::makeFacebookLoginUrl($returnUrl), array('class' => 'facebook-login2')); ?>       
                    <?php endif; ?>            
                </div>    
            </div>
        </div>             
    </div>
    <div class="row-fluid" style="margin-top:20px;">        
        <div class="span8 offset2">            
            <p style="text-align:center;">Để sử dụng chức năng này bạn cần kết nối với Facebook.</p>
        </div>
    </div>
</div>

frontend/views/user/login.php
<?php
$this->pageTitle = LanguageUtil::t('Sign In').' ITAKE';

//$this->showHeader = false;
?>
<div class="container-fluid" style="margin-top: 24px;">
    <div class="row-fluid">
        <div class="span8 offset2">
        <h2 class="form-signin-heading"><i class="icon-signin"></i>  <?php LanguageUtil::echoT('Sign In'); ?></h2>          
        <hr/>
        </div>
    </div>
    <div class="row-fluid" style="margin-top: 30px;">
        <div class="span4 login-panel offset2" style="border-right:dashed 1px #ccc;">
            <?php
            $this->widget('bootstrap.widgets.TbAlert', array(
                'block' => true,
                'fade' => true,
                'closeText' => '×',
                'alerts' => array(
                    'error' => array('block' => true, 'fade' => true, 'closeText' => '×'),
                ),
            ));
            ?>
            <?php
            $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
                'type' => 'inline',
                'htmlOptions' => array(
                    'class' => 'form-signin'
                )
                    ));
            ?>
            <?php
            $this->widget('bootstrap.widgets.TbAlert', array(
                'block' => true,
                'fade' => true,
                'closeText' => '×',
                'alerts' => array(
                    'success' => array('block' => true, 'fade' => true, 'closeText' => '×'), // success, info, warning, error or danger
                ),
            ));
            ?>            
            <?php echo $form->errorSummary($model); ?>
            <?php
            echo $form->textFieldRow($model, 'username', array(
                'placeholder' => LanguageUtil::t('Email'),
                'class' => 'input-block-level'
            ));
            ?>
            <?php
            echo $form->passwordFieldRow($model, 'password', array(
                'placeholder' => LanguageUtil::t('Password'),
                'class' => 'input-block-level'
            ));
            ?>
            <?php //echo $form->checkBoxRow($model, 'rememberMe', array('value=1')); ?>
            <div style="float:right;width:100%;text-align: right; font-size:0.9em;">
                <?php echo CHtml::link(LanguageUtil::t('Forgot password').'?', array('/user/forgetPassword')); ?>                
            </div>  
            <div style="float:right;width:100%;">
                <button class="btn btn-primary login" type="submit" style="width:100%;height:50px;font-size:1.3em;"><?php LanguageUtil::echoT('Sign In'); ?></button>
            </div>           
            

            <style>
                #gplusSignIn {
                    display: inline-block;      
                    color: white;
                    width: 350px;      
                    height: 77px;
                    cursor: pointer;
                    background: url('../images/gplus_btn.png') no-repeat;
                    white-space: nowrap;
                }
                #customBtn:hover {
                    background: #e74b37;
                    cursor: hand;
                }
                span.label {
                    font-weight: bold;
                }
                span.icon {      
                    display: inline-block;
                    vertical-align: middle;
                    width: 35px;
                    height: 35px;      
                } 
            </style>
        </div>        
        <div class="span4">
             <div style="float:right;width:100%;margin-top: 40px;">
            <!--     <p style="font-family: 'Segoe UI Light',Arial,Helvetica,sans-serif;font-size:1.1em;">Dễ dàng chia sẽ tin đăng. ITAKE kết nối tới facebook của bạn để việc bán hàng của bạn nhanh chóng hơn, tiếp thị sản phẩm thêm hiệu quả. Hãy đăng nhập bằng facebook để chia sẻ sản phẩm bạn tới bạn bè trên facebook một cách tốt nhất.</p> -->                
                <h4 class="rb-h4" style="text-align: center;"><?php LanguageUtil::echoT('OR SIGN IN BY') ?></h4>
                <div class="fb-login-wrapper"> 
                    <?php if(Yii::app()->language=='vi'): ?>
                    <?php echo CHtml::link('', FacebookUtil::makeFacebookLoginUrl($returnUrl), array('class' => 'facebook-login')); ?>       
                    <?php else: ?>            
                      <?php echo CHtml::link('', FacebookUtil::makeFacebookLoginUrl($returnUrl), array('class' => 'facebook-login2')); ?>       
                    <?php endif; ?>            
                </div>    
            </div>
        </div>       
        <?php $this->endWidget(); ?> 
    </div>
    <div class="row-fluid" style="margin-top:20px;">        
        <div class="span8 offset2">
            <hr/>
            <p style="text-align:center;"><?php LanguageUtil::echoT('You do not have an account') ?>?  <?php echo CHtml::link(LanguageUtil::t('Create an account'), array('/user/register')); ?></p>
        </div>
    </div>
</div>

frontend/views/user/successSendForgetPassword.php
<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>