backend/controllers/SiteController.php
<?php
/**
 * SiteController.php
 *
 * @author: antonio ramirez <antonio@clevertech.biz>
 * Date: 7/24/12
 * Time: 1:21 AM
 */

class SiteController extends Controller
{
	/**
	 * @return array list of action filters (See CController::filter)
	 */
	public function filters()
	{
		return array('accessControl');
	}

	/**
	 * @return array rules for the "accessControl" filter.
	 */
	public function accessRules()
	{
		return array(			
			array('allow', // Allow all actions for logged in users ("@")          
			),
			array('deny'), // Deny anything else
		);
	}

	/**
	 *
	 * @return array actions
	 */
	public function actions()
	{
		return array(
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
				'foreColor' => 0x0099CC,
			),
			'page' => array(
				'class' => 'CViewAction',
			),
		);
	}

	/**
	 * Renders index page
	 */
	public function actionIndex()
	{         
		$this->render('index');
	}


	/**
	 * Action to render the error
	 * todo: design proper error page
	 */
	public function actionError()
	{
		if ($error = app()->errorHandler->error)
		{
			if (app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Action to render login form or handle user's login
	 * and redirection
	 */
	public function actionLogin()
	{
		$model = new BackendLoginForm();

		if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form')
		{
			echo CActiveForm::validate($model, array('username', 'password', 'verifyCode'));
			Yii::app()->end();
		}

		if (isset($_POST['BackendLoginForm']))
		{
			$model->attributes = $_POST['BackendLoginForm'];
			if ($model->validate(array('username', 'password', 'verifyCode')) && $model->login())
				$this->redirect(user()->returnUrl);
		}

		$sent = r()->getParam('sent', 0);
		$this->render('login', array(
			'model' => $model,
			'sent' => $sent,
		));
	}

	/**
	 * This is the action that handles user's logout
	 */
	public function actionLogout()
	{
		user()->logout();
		$this->redirect(app()->homeUrl);
	}

}

frontend/controllers/SiteController.php
<?php
class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }
    public function init() {        
        return parent::init();
    }
    public function filters() {
        return array(
            array(
                'frontend.components.FacebookAccessCheckerFilter + index,facebook,landing'
            )
        );
    }

    public function behaviors() {
        return array(
            'seo' => array('class' => 'frontend.extensions.seo.components.SeoControllerBehavior')
        );
    }

    public function actionCity($city) {    
        CityUtil::setSelectedCityId($city);        
        $this->actionIndex();
    }

    public function actionSuggest($term) {
        $adapter = new SuggestAdapter();
        $adapter->setKeyword($term);
        $suggests = $adapter->getSuggestion();
        echo json_encode($suggests);
    }

    public function actionSortType($type) {
        SolrSortTypeUtil::getInstance()->setSortType($type);
        $city = UserRegistry::getInstance()->getValue('City');
        $category = Yii::app()->session->get('LastCategory', null);
        $keyword = Yii::app()->session->get('LastKeyword', null);
        $this->redirect($this->createUrl('index', array(
                    'keyword' => null,
                    'category' => $category,
                    'page' => 0
        )));
    }

    public function actionFacebook() {
        $url = $this->createUrl('index', array(
            'keyword' => null,
            'category' => Yii::app()->session['LastCategory'],
            'facebook' => 1,
            'page' => 0,
            'status' => Product::STATUS_ACTIVE
        ));
        $this->redirect($url);
    }

    public function actionSold() {
        $url = $this->createUrl('index', array(
            'keyword' => null,
            'category' => Yii::app()->session['LastCategory'],
            'facebook' => 0,
            'page' => 0,
            'status' => Product::STATUS_SOLD
        ));
        $this->redirect($url);
    }
    
    public function actionCategory($category,$city = null){                      
        if($city){            
            CityUtil::setSelectedCityId($city);
        }
        
        $this->actionIndex(null,$category);
    }

    public function actionIndex($keyword = null, $category = null, $facebook = 0, $page = 0, $status = Product::STATUS_ACTIVE) {              
        //echo StringUtil::replaceRepeatCharacter('baf---_---a', '-', '');exit;
        if (Yii::app()->user->isGuest && isset(Yii::app()->request->cookies['usercity_ck'])) {
            CityUtil::setSelectedCityId(Yii::app()->request->cookies['usercity_ck']->value);
        }
        $keyword = trim(filter_var($keyword, FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES));
        Yii::app()->session['LastPageNumber'] = $page;
        Yii::app()->session['LastCategory'] = $category;
        Yii::app()->session['LastKeyword'] = $keyword;

        $categoryModel = null;
        if ($category != null) {
            $categoryModel = Category::model()->findByPk($category);
        }
        if ($keyword != '') {
            $this->pageTitle = Yii::app()->name . ' - Kết quả tìm kiếm cho từ khóa ' . $keyword;
        } else if ($categoryModel != null) {
            $this->pageTitle = Yii::app()->name . ' - Danh mục ' . $categoryModel->name;
        } else if ($facebook) {
            $this->pageTitle = Yii::app()->name . ' - Sản phẩm được đăng từ bạn bè của bạn';
        }


        $city = CityUtil::getSelectedCityId();
        $empty = true;
        $nextPageLink = false;
        $productList = array();
        $requiredFacebookLogin = false;
        $numFound = 0;
        $locationAddress = null;
        $locationCity = null;
        if ($facebook && !FacebookUtil::getInstance()->doUserHaveEnoughUploadPermission()) {
            $requiredFacebookLogin = true;
        } else {
            $solrAdapter = new SolrSearchAdapter();
            $solrAdapter->setSortType(SolrSortTypeUtil::getInstance()->getCurrentSortType());
            $solrAdapter->categoryId = $category;
            $solrAdapter->cityId = $city;
            $solrAdapter->page = $page;
            $solrAdapter->pageSize = 12;
            $solrAdapter->country = Yii::app()->country->getId();
            $solrAdapter->keyword = $keyword;
            $solrAdapter->status = $status;
            $solrAdapter->facebookFriend = $facebook;


            if ($solrAdapter->getSortType() == SolrSearchAdapter::TYPE_LOCATION) {
                $lat = UserLocationUtil::getInstance()->lat;
                $lng = UserLocationUtil::getInstance()->lng;
                $locationAddress = UserLocationUtil::getInstance()->address;
                $locationCity = UserLocationUtil::getInstance()->city;
                if ($lat != null && $lng != null) {
                    $solrAdapter->setLocation($lat, $lng);
                }
            }
            Yii::beginProfile('search');
            $resultSet = $solrAdapter->search();
            Yii::endProfile('search');

            $productList = $resultSet->productList;
            $numFound = $resultSet->numFound;
            $empty = $page * $solrAdapter->pageSize > $resultSet->numFound;
            $params = array(
                'keyword' => $keyword,
                'category' => $category,
                'facebook' => $facebook,
                'page' => $page + 2,
                'status' => $status
            );
            $nextPageUrl = $this->createNextUrl($params);
            $nextPageLink = CHtml::link('Next', $nextPageUrl, array(
                        'class' => 'nextPageLink',
            ));
        }
        $canShowRequireVerifyEmail = false;
        if(Yii::app()->user->isGuest == false && false == UserEmail::isEmailVerified(Yii::app()->user->model->email)){
            $canShowRequireVerifyEmail = true;
        }
        if (!Yii::app()->request->isAjaxRequest) {
            $this->render('index', array(
                'numFound' => $numFound,
                'canShowRequireVerifyEmail'=>$canShowRequireVerifyEmail,
                'productList' => $productList,
                'nextPageLink' => $nextPageLink,
                'keyword' => $keyword,
                'categoryModel' => $categoryModel,
                'category' => $category,
                'status' => $status,
                'facebook' => $facebook,
                'empty' => $empty,
                'locationAddress' => $locationAddress,
                'locationCity' => $locationCity,
                'city' => $city,
                'requiredFacebookLogin' => $requiredFacebookLogin
            ));
        } else {
            $html = '';
            if ($empty == false) {
                foreach ($productList as $product) {
                    $html.=$product->renderHtml('home-', false);
                }
                $this->renderAjaxResult(true, array(
                    'items' => $html,
                    'count' => count($productList)
                ));
            } else {
                $this->renderAjaxResult(true, array(
                    'count' => 0
                ));
            }
        }
    }

    protected function createNextUrl($params) {
        return Yii::app()->controller->createAbsoluteUrl('/site/index', $params);
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                $this->renderAjaxResult(false, array(
                    'code' => $error['code'],
                    'message' => $error['message']
                ));
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact() {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $name = '=?UTF-8?B?' . base64_encode($model->name) . '?=';
                $subject = '=?UTF-8?B?' . base64_encode($model->subject) . '?=';
                $headers = "From: $name <{$model->email}>\r\n" .
                        "Reply-To: {$model->email}\r\n" .
                        "MIME-Version: 1.0\r\n" .
                        "Content-type: text/plain; charset=UTF-8";

                mail(Yii::app()->params['adminEmail'], $subject, $model->body, $headers);
                Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid

frontend/views/site/_board.php
<div id="productContainer" style="display:none;" class="productBoard">
<div class="grid-sizer"></div>
<?php foreach($productList as $product):?>
    <?php if($product!==null)echo $product->renderHtml('home-'); ?>
<?php endforeach; ?>

</div>
<?php echo $nextPageLink; ?>

frontend/views/site/index.php
<?php
/* @var $this SiteController */
/* @var $error array */
Yii::beginProfile('RenderSiteIndex');
$this->pageTitle = Yii::app()->name . ' - '. LanguageUtil::t("ITAKE.ME ! It's easy and so simple to internet marketing on your products, classified ads on Fashion, Mobile and Tablet, Desktop and Latop, Camera and Electrical Devices, Handmade and Art, Services, Real Estate, Car and Motobike, Others");
?>
<?php
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/masonry.pkgd.min.js', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/jquery.infinitescroll.min.js', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile('http://maps.google.com/maps/api/js?sensor=true', CClientScript::POS_HEAD,false);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/gmaps.js', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/site.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/productDetails.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/productControl.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/map-util.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/user-location.js', CClientScript::POS_END);
$cityList = json_encode(CityUtil::getCityList(true));
$jsCategory = $category !=null ? $category:'null';
$jsKeyword = $keyword!=null ? $keyword:'';
Yii::app()->clientScript->registerScript('data',"
    var cityList = $cityList;
    var category = $jsCategory;
    var facebook = $facebook;
    var city = $city;
    var status= $status;
    var keyword = '$jsKeyword';
    ",  CClientScript::POS_HEAD);
$cityId = CityUtil::getSelectedCityId();
$canShowCityDialog = $cityId !=0 ? 'false':'true';
Yii::app()->clientScript->registerScript('showcity',"var canShowCityDialog = $canShowCityDialog;",CClientScript::POS_HEAD);

?>
<div class="container-fluid">
    <div class="row-fluid">

        <div class="sort-bar visible-desktop">
            <div class="selectedCategoryTab"> 
            <?php if (isset($categoryModel) && $categoryModel != null): ?>
                <?php $this->pageTitle = LanguageUtil::t($categoryModel->name) . " ".LanguageUtil::t('on')." ITAKE.ME" ?>
            
                <h1 class="title_font" style="font-size:1.5em;">
                    <?php echo $categoryModel->getIconAndNameHtml()."   ";?>
                    <?php if (strlen(CityUtil::getCityName($city))>0): ?>
                        <?php LanguageUtil::echoT($categoryModel->name);echo ' '; LanguageUtil::echoT('in');?>  <?php echo CityUtil::getCityName($city); ?>
                    <?php  else:?>     
                        <?php LanguageUtil::echoT($categoryModel->name);?>
                    <?php endif; ?>


                </h1>                                     
                <script>
                    $(function() {
                        var counter = 0;
                        var styleName = '<?php echo $categoryModel->styleName ?>';
                        $('.nav-text.all-cat-wrap').removeClass('selected');
                        $(".nav-text."+styleName.replace(' ','.')).addClass('selected');
                   
                    });
                </script>

            <?php endif; ?>
               </div>     
            <?php
                $currentSortType = SolrSortTypeUtil::getInstance()->getCurrentSortType();
                if($facebook==0&&(!isset($_GET['status'])||$_GET['status']!=3))
                    $sortTypeLink = SolrSortTypeUtil::getInstance()->makeSortTypeUrl($currentSortType);
                else
                    $sortTypeLink = "nothing";
            ?>
            <div class="pagination pagination-centered" style="z-index: 999;position: relative;">
              <ul>
         
              <?php foreach (SolrSortTypeUtil::getInstance()->getSortTypeLinkList() as $link): ?>
                  <?php if(strpos($link, $sortTypeLink)!== FALSE):?>
                      <li class="active"><?php echo $link; ?></li>
                  <?php else: ?>
                      <li><?php echo $link; ?></li>
                  <?php endif; ?>
                  <?php break;?>
              <?php endforeach; ?>
                  
                <?php if($facebook==1&&isset($_GET['status'])&&$_GET['status']!=3):?>
                <li class="active">
                <?php else: ?>
                <li >
                <?php endif;?>
                    
                    <?php 
               
                        echo CHtml::link(
                                LanguageUtil::t('Facebook friend'),
                                $this->createUrl('/site/facebook')
                        );
                    
                    ?>
                </li>
              <?php if(isset($_GET['status'])&&$_GET['status']==3):?>
              <li class="active">
                  <?php else: ?>
              <li >
                  <?php endif;?>
                    <?php echo CHtml::link(LanguageUtil::t('Product sold'),
                        $this->createUrl('/site/sold'
                        )
                    );?>
                </li>
              </ul>
            </div>
        </div> 
        <div id="categories-bar" class="visible-desktop">          
            <div class="row-fluid">     

                <ul>
                    <li><a href="<?php echo CityUtil::makeSelectCityUrl($cityId) ?>" title="<?php echo LanguageUtil::t('All')?>"><span class="nav-text all-cat-wrap selected mark"><small class="all-cat"></small><em></em>     &nbsp&nbsp<?php LanguageUtil::echoT('All') ?></span></a></li>                                                      
                    <?php foreach (CategoryUtil::getCategoryList() as $category): ?>
                        <li><a href="<?php echo $category->getUrl(); ?>" data-toggle="tooltip" title='<?php echo LanguageUtil::t($category->name)?>'><span class="nav-text <?php echo $category->getStyleName(); ?>"><small><i class="<?php echo $category->icon; ?> icon-large"></i> <em></em></small>      &nbsp&nbsp<?php LanguageUtil::echoT( $category->name);  ?></span></a></li>
                    <?php endforeach; ?>                    
                </ul>
            </div>       
        </div>        
        <div class="row-fluid" id="fixWidthMasory" class="visible-desktop"></div>
        <div class="row-fluid">
        <div class="span2 visible-desktop" id="menuWidthBase" style="height: 1000px;" class=""><p></p></div>
            <div class="span10">
                <div class="row-fluid" >
                     <div class="span12">
                        
                        <div  id="wrapper_productContainer">
                            <?php if($canShowRequireVerifyEmail):?>
                            <div id='requireConfirmEmail' class='alert alert-info'>
                                <p>
                                    Email của bạn chưa được xác thực, hãy xác thực email để nhận được thông báo mới nhất từ iTake.vn.
                                    <br/>
                                    Nhấn vào gửi email xác thực nếu bạn chưa nhận được email
                                    
                                    <?php echo CHtml::link('Gửi email xác thực','/user/sendVerifyEmail',array(
                                        'class'=>'btn btn-primary pull-right'
                                    )); ?>
                                </p>
                                <br/>                       
                            </div>
                            <?php endif; ?>
                            <div class="hidden-desktop">
                                <center><?php echo CHtml::dropDownList('selectCategory', $category,  CHtml::listData(CategoryUtil::getCategoryList(),'id','name'));?></center>
                            </div>                
                            <?php if (trim($keyword) != ''): ?>
                                <div class="alert alert-info">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <b>Có <?php echo $numFound; ?> kết quả với từ khóa <?php echo $keyword; ?></b></div>                
                            <?php endif; ?>
                            <?php if($locationAddress !=null):?>
                                <div class="alert alert-info">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    Đang hiển thị các sản phẩm gần địa điểm <?php echo $locationAddress; ?>, <?php echo $locationCity; ?> | 
                                    <?php echo CHtml::link('<i class="icon-remove"></i> Xóa vị trí',array('/site/removeLocation'));?>
                                </div>
                            <?php endif; ?>
                            <?php if($facebook && count($productList)==0):?>
                            <div class="row-fluid">
                                <div class="span6 offset3">
                                    <?php if(FacebookUtil::getInstance()->doUserHaveEnoughUploadPermission() ==false):?>
                                        <p class="alert alert-info center">
                                            <span class="icon-stack icon-2x">
                                              <i class="icon-circle icon-stack-base"></i>
                                              <i class="icon-facebook icon-light"></i>
                                            </span>
                                            <br>
                                            Bạn cần kết nối tài khoản của bạn với Facebook để sử dụng chức năng này.
                                        </p>
                                        <div class="row-fluid center">
                                        <?php echo FacebookUtil::getInstance()->makeFacebookLoginLink('Click để kết nối iTake với Facebook',  Yii::app()->createUrl("site/facebook")); ?>
                                        </div>
                                    <?php else:?>
                                    <p class="alert alert-info center">
                                         <span class="icon-stack icon-2x">
                                              <i class="icon-circle icon-stack-base"></i>
                                              <i class="icon-smile icon-light"></i>
                                            </span>
                                        <br>
                                        Hiện tại chưa có sản phẩm nào được bán từ bạn bè của bạn, hãy mời họ sử dụng itake.
                                    </p>
                                    <?php endif; ?>
                                    <hr class="margin-top-10"/>
                                    <div class="fb-like center margin-top-10" data-href="<?php echo Yii::app()->getBaseUrl(true); ?>" data-width="auto" data-show-faces="true" data-send="true"></div>
                                </div>
                            </div>
                            <?php endif; ?>
                            <?php
                            Yii::beginProfile('RenderProductList'); 
                            $this->renderPartial('/site/_board', array(
                                'productList' => $productList,
                                'nextPageLink' => $nextPageLink
                            ));
                            Yii::endProfile('RenderProductList');
                            ?>
                            <div id="loadingText"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<?php echo $this->renderPartial('/site/_productDialog', array(), true, false); ?>
<?php $this->renderPartial('partial/cityDialog',array()); ?>
<?php Yii::endProfile('RenderSiteIndex'); ?>

frontend/views/site/list.php
<?php
/* @var $this SiteController */
/* @var $error array */
Yii::beginProfile('RenderSiteIndex');
$this->pageTitle = Yii::app()->name . ' - '. LanguageUtil::t("ITAKE.ME ! It's easy and so simple to internet marketing on your products, classified ads on Fashion, Mobile and Tablet, Desktop and Latop, Camera and Electrical Devices, Handmade and Art, Services, Real Estate, Car and Motobike, Others");
?>
<?php
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/masonry.pkgd.min.js', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/jquery.infinitescroll.min.js', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile('http://maps.google.com/maps/api/js?sensor=true', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/gmaps.js', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/site.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/productDetails.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/productControl.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/map-util.js?id=1', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/nada/user-location.js?id=1', CClientScript::POS_END);
$cityList = json_encode(CityUtil::getCityList(true));
Yii::app()->clientScript->registerScript('data',"
    var cityList = $cityList;
    ",  CClientScript::POS_HEAD);
?>
<div class="container-fluid">
    <div class="row-fluid">

        <div class="sort-bar">
                    <div class="pagination pagination-centered" >
                      <ul>
                         <?php foreach (SolrSortTypeUtil::getInstance()->getSortTypeLinkList() as $link): ?>
                            <li><?php echo $link; ?></li>
                        <?php endforeach; ?>               
                        <li>
                            <?php echo CHtml::link('Bạn bè Facebook',
                                $this->createUrl('/site/facebook',
                                array(
                                    'category'=>$categoryModel->id)
                                )
                            );?>
                        </li>
                        <li>
                            <?php echo CHtml::link('Đã bán',
                                $this->createUrl('/site/sold',
                                array(
                                    'category'=>$categoryModel->id)
                                )
                            );?>
                        </li>
                      </ul>
                    </div>
        </div> 
        <div id="categories-bar">          
            <div class="row-fluid">     

                <ul>
                    <li><a href="<?php echo Yii::app()->createUrl('/site/index') ?>" title="<?php echo LanguageUtil::t('All')?>"><span class="nav-text all-cat-wrap selected mark"><small class="all-cat"></small><em></em>     &nbsp&nbsp<?php LanguageUtil::echoT('All') ?></span></a></li>                                                      
                    <?php foreach (CategoryUtil::getCategoryList() as $category): ?>
                        <li><a href="<?php echo $category->getUrl(); ?>" data-toggle="tooltip" title='<?php echo LanguageUtil::t($category->name)?>'><span class="nav-text <?php echo $category->getStyleName(); ?>"><small><i class="<?php echo $category->icon; ?> icon-large"></i> <em></em></small>      &nbsp&nbsp<?php LanguageUtil::echoT( $category->name);  ?></span></a></li>
                    <?php endforeach; ?>                    
                </ul>
            </div>    
            <div class="selectedCategoryTab"> 
            <?php if (isset($categoryModel) && $categoryModel != null): ?>
                <?php $this->pageTitle = $categoryModel->name . " ".LanguageUtil::t('on')." ITAKE.ME" ?>
            
                <h1>
                    <?php echo $categoryModel->getIconAndNameHtml()."   ";?>
                    <?php if (strlen(CityUtil::getCityName($city))>0): ?>
                        <?php LanguageUtil::echoT($categoryModel->name);echo ' '; LanguageUtil::echoT('in');?>  <?php echo CityUtil::getCityName($city); ?>
                    <?php  else:?>     
                        <?php LanguageUtil::echoT($categoryModel->name);?>
                    <?php endif; ?>


                </h1>                                     
                <script>
                    $(function() {
                        var counter = 0;
                        var styleName = '<?php echo $categoryModel->styleName ?>';
                        $('.nav-text.all-cat-wrap').removeClass('selected');
                        $(".nav-text."+styleName.replace(' ','.')).addClass('selected');
                   
                    });
                </script>

            <?php endif; ?>
               </div>        

        </div>        
        <div class="row-fluid" id="fixWidthMasory"></div>
        <div class="span9" style="margin-left:50px;">            
            <div class="row-fluid" id="wrapper_productContainer" style="margin-top:120px;"   >  
                <hr style="position:relative; top:-40px;"/>
                <?php if (trim($keyword) != ''): ?>
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <b>Có <?php echo $numFound; ?> kết quả với từ khóa <?php echo $keyword; ?></b></div>                
                <?php endif; ?>
                <?php if($locationAddress !=null):?>
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        Đang hiển thị các sản phẩm gần địa điểm <?php echo $locationAddress; ?>, <?php echo $locationCity; ?> | 
                        <?php echo CHtml::link('<i class="icon-remove"></i> Xóa vị trí',array('/site/removeLocation'));?>
                    </div>
                <?php endif; ?>
                <?php
                Yii::beginProfile('RenderProductList'); 
                $this->renderPartial('/site/_board', array(
                    'productList' => $productList,
                    'nextPageLink' => $nextPageLink
                ));
                Yii::endProfile('RenderProductList');
                ?>
                <div id="loadingText"></div>
            </div>
            </div>
    </div>
</div>

<?php echo $this->renderPartial('/site/_productDialog', array(), true, false); ?>

<?php Yii::endProfile('RenderSiteIndex'); ?>